name: Build and Test
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                    "-DMY_CUSTOM_OPTION=ON"
                ]
              }
            }
